spring.datasource.url=jdbc:mysql://localhost:3306/billing_app
spring.datasource.username=root
spring.datasource.password=root1234

spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path=/api/v1.0

aws.access.key=AKIAU4OEDGF3ZZ7KAL6C
aws.secret.key=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
aws.region=ap-south-1
aws.bucket.name=billing-software-shani01